DROP TABLE IF EXISTS WORD;
DROP TABLE IF EXISTS SENTENCE;
DROP TABLE IF EXISTS SENTENCE_WORD;
--TODO DOPLNIT DROPY
CREATE TABLE WORD
(
    WORD_ID SERIAL,
    WORD  varchar(250) NOT NULL,
    WORD_CATEGORY  CHAR(10) NOT NULL,
    PRIMARY KEY (WORD_ID),
    UNIQUE (WORD)
);

CREATE TABLE SENTENCE
(
    SENTENCE_ID SERIAL,
    VIEWS  int NOT NULL,
    ADDET_DT timestamp NOT NULL,
    PRIMARY KEY (SENTENCE_ID)
);
CREATE TABLE SENTENCE_WORD
(
    SENTENCE_WORD_ID SERIAL,
    WORD_ID  int4 NOT NULL,
    SENTENCE_ID INT4 NOT NULL,
    POSITION INT NOT NULL,
    PRIMARY KEY (SENTENCE_WORD_ID)
);

ALTER TABLE SENTENCE_WORD ADD CONSTRAINT FKSENTENCE_WORD1 FOREIGN KEY (WORD_ID) REFERENCES WORD (WORD_ID);
ALTER TABLE SENTENCE_WORD ADD CONSTRAINT FKSENTENCE_WORD2 FOREIGN KEY (SENTENCE_ID) REFERENCES SENTENCE (SENTENCE_ID);